version: '3'

services:
  sqlshare:
    build: .
    environment:
      SQLSHARE_DB: postgres://postgres:root@postgres/sqlshare
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: sqlshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/sqlshare-init.sql:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    # volume to persist postgres data
